language: python
python:
  - "3.5"

env:
  global:
    - DJANGO_SETTINGS_MODULE="website.travis_settings"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - python3 manage.py migrate

# command to run tests
script: python3 manage.py test