language: python
python:
  - "3.5"

env:
  global:
    - DJANGO_SETTINGS_MODULE="website.travis_settings"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - pwd;
  - rm -rf db.sqlite3;
  - touch db.sqlite3;
  - cd workflow && mkdir migrations;
  - cd ..;
  - rm -rf workflow/migrations/*;
  - touch workflow/migrations/__init__.py;
  - rm -rf mainsite/migrations/*;
  - cd mainsite && mkdir migrations;
  - touch mainsite/migrations/__init__.py;
  - cd ..;
  - python3 manage.py makemigrations;
  - python3 manage.py migrate;

# command to run tests
script: python3 manage.py test